### ISSUE TITLE
Some music seems to be missing. Loose songs and songs stored in a subdirectory don't appear in the list

### ISSUE THREAD

**Issue by smithdtyler** [smithdtyler/prettygoodmusicplayer#46]

**Comment by smithdtyler** [comment]
Marking this as an enhancement because the current version is working as designed - it doesn't search beyond the specified folder structure.

**Comment by xoyteam** [comment]
I have same touble...

**Comment by smithdtyler** [comment]
I will work on this.

**Comment by xoyteam** [comment]
I checked again and I think that is the problem https://github.com/smithdtyler/prettygoodmusicplayer/issues/46

**Comment by smithdtyler** [comment]
Here's my plan:
- Any songs in the base "music" folder will be added at the end of the list of artists. 
- Any songs in the artist folder will be added at the end of the list of albums
 - Any loose songs in directories inside an album folder will be added to the album's song list (at the end).

**Comment by deveee** [comment]
One thing is that these songs are not displayed and then can't be selected to play. Other thing is that when I have in the list for example:
```
- ALL
- Album 1
- Album 2
- Song 1
- Song 2
```
and I click ```ALL```, then I would like to play whole directory (with Album 1, Album 2, Song 1 and Song 2). Atm. the part of songs is ignored. The ```ALL``` button should open recursively whole directory with subdirectories.

**Comment by smithdtyler** [comment]
I believe the issue mentioned in the April 9th comment can be resolved by removing the condition at line 127 of SongList.java. I'll address this ASAP.

**Comment by smithdtyler** [comment]
I've implemented the 'All' option as you described. Thanks for your patience.
