### ISSUE TITLE
Navigating to now playing from the explorer view

### ISSUE THREAD

**Issue by smithdtyler** [smithdtyler/prettygoodmusicplayer#47]

**Comment by deveee** [comment]
Here is the general idea:
http://deve.koliber.pl/prettygoodmusicplayer/nowplaying.patch

Sorry about whitespaces...

What do you think about it? The icon may be misunderstood... Currently it looks like the button for playing selected directory, not for switching to "now playing" screen. Maybe something like this could be better:
https://cdn2.iconfinder.com/data/icons/windows-8-metro-style/512/cd.png

Btw. don't you think that AlbumList, ArtistList and SongList could use one common parent class to avoid code duplication?

**Comment by smithdtyler** [comment]
I will take a look at your suggested patch this weekend (at the latest).

*Btw. don't you think that AlbumList, ArtistList and SongList could use one common parent class to avoid code duplication?*

Agreed, there's definitely some room for refactoring there.

**Comment by deveee** [comment]
Atm. this is far from perfect. I just would like to know if you agree
with this idea or maybe you want to do it in totally different way
(for example like in VLC).

**Comment by smithdtyler** [comment]
Started incorporating your suggestions in this branch: https://github.com/smithdtyler/prettygoodmusicplayer/tree/jumptonowplaying

**Comment by smithdtyler** [comment]
I'm going to do some more refactoring in this next release, so there might be a little bit of chaos on that branch :)

**Comment by smithdtyler** [comment]
I started merging stuff into AbstractMusicList.

**Comment by deveee** [comment]
Thanks for your work! I personally prefer separated button, but it's your choice. I could create simple CD icon :)

**Comment by smithdtyler** [comment]
Could you make a screenshot of what you're thinking? The whole screen, not
just the button

**Comment by deveee** [comment]
I mean something like this:
![screenshot_2015-06-27-21-10-40](https://cloud.githubusercontent.com/assets/5108558/8393483/1ec1070e-1d11-11e5-80e0-23c28facb2a5.png)

but with different icon, because "play" suggest that you are starting playing current directory.

**Comment by smithdtyler** [comment]
Gotcha. I think I need to go with my original approach because some phones don't have a dedicated 'menu' button, and put their menu button where the 'now playing' button would go.

However, your comment about a button which would play the current directory actually gives me an idea... I might want to add two-three buttons at the bottom. One for "shuffle current directory" one for "play current directory" and one for "now playing". What would you think of that?

![screen shot 2015-06-28 at 8 15 33 am](https://cloud.githubusercontent.com/assets/8142684/8396500/e75a0be6-1d6d-11e5-87f7-d06090e59d6e.png)

**Comment by deveee** [comment]
You can even add something like this at the bottom
http://blog.sudobits.com/wp-content/uploads/2012/06/andless.png and then
"now playing" screen won't be needed at all ;-)

I'm not convinded to the button bar at the bottom. Most of the buttons are
probably used rarely (settings, exit, shuffle, maybe "repeat one" in
future). And it's enough that they are available in "menu" button.
Additional button bar would make the list with songs smaller.

Btw. "menu" button in my phone is available in the right button (rectangle
on your screenshot).

**Comment by smithdtyler** [comment]
I opted to just stick with the menu option. Thanks for the input!
