### ISSUE TITLE
Small screen size does not show full font

### ISSUE THREAD

**Issue by ole-tange** [smithdtyler/prettygoodmusicplayer#63]
When playing on LGE400 (240x320) the fonts are cut in half. Suggest using a smaller font size for small screens.

**Comment by smithdtyler** [comment]
F-Droid has the fix now, please let me know if I can close this defect. Thanks!

**Comment by smithdtyler** [comment]
I haven't heard anything on this defect in a while, so I'm going to assume my update fixed the issue.
