### ISSUE TITLE
Delay in detecting unplugged headphones

### ISSUE THREAD

**Issue by deveee** [smithdtyler/prettygoodmusicplayer#66]
I have enabled property which detects if my headphones are unplugged during playing music. In this case player state is changed to "paused", as expected. But I can observe 2-3 seconds delay before state is changed. During this time music is playing with phone's speaker. Ideally it shouldn't be played at all when headphones are unplugged.

**Comment by smithdtyler** [comment]
Thanks for putting this together, I think it's a pretty good solution. I'll merge it in and try it out.

**Comment by smithdtyler** [comment]
I think ultimately I'd like to make the behavior configurable, e.g. 

On headphone disconnect:
1. Pause immediately
2. Pause after 1 sec grace period
3. Pause, but resume on re-insertion within one second

**Comment by smithdtyler** [comment]
Brainstorming implementation options:
As a menu option:

"Headphone Disconnect Behavior"
* Pause Immediately
* Pause after 1 Second
* Resume on Reconnect within 5 Seconds

**Comment by deveee** [comment]
Maybe also add an option to resume on reconnect without time limit? This is what I did in my patch. When player was paused by unplugging phones, it can be resumed by plugging it again. 
In most players I see two separated properties:
 - pause on disconnect
 - resume on reconnect   (without time limit)
The second option isn't necessary, but some peopel may use it.

Btw. your player is quite good :) Did you write it from scratch or is it based on code from other players?

**Comment by smithdtyler** [comment]
Sure, I can add that option. 

Thanks! I mostly wrote it from scratch. I used a couple of open source projects as reference examples:

[Media Button Router](https://play.google.com/store/apps/details?id=com.harleensahni.android.mbr&hl=en)

[Android-File-Explore](https://github.com/mburman/Android-File-Explore)

Thanks for the feedback! It's fun to work on a project like this with engaged and helpful users :)

**Comment by smithdtyler** [comment]
Nominal implementation is in [this branch](https://github.com/smithdtyler/prettygoodmusicplayer/tree/66_pausebehavior)

I haven't tested it yet.  I will close this ticket once I've successfully tested all of the modes and merged the fix into master.

**Comment by smithdtyler** [comment]
Tested and merged into master. 

I occasionally still had an issue with a split second of music playing after the headphones are unplugged, but I don't think there's anything I can do about it - I'm sending a "pause" as soon as I get an "unplugged" notification.

**Comment by deveee** [comment]
Thanks a lot for adding this feature! I will test current version today.

Atm. I am rather busy because we are before Supertuxkart release, but I can try to find few minutes to make Polish translations :) Are you interested in it?

**Comment by smithdtyler** [comment]
Absolutely, that would be great!
