### ISSUE TITLE
Easy 20 seconds jumps in Audiobook Mode with long pressed Vol Keys

### ISSUE THREAD

**Issue by qkiel** [smithdtyler/prettygoodmusicplayer#67]
Sometimes unexpected things steal our focus when we listen to audiobooks. It's not that easy to rewind lost 20 seconds and get back to the story like nothing ever happend. What if we could just press and hold volume keys to jump few moment in time?

**Comment by smithdtyler** [comment]
Sounds like a good feature to add.

**Comment by smithdtyler** [comment]
I'm working on implementing this. I don't know if I'll be able to use the
volume keys (I haven't researched it yet). I'm really hesitant to do
anything that requires additional application permissions, so if getting
volume presses requires more permissions I'll have to use some other input
for the "jump back" functionality.

**Comment by smithdtyler** [comment]
I decided to provide this functionality as a button on the "Now Playing" screen, as well as (when Audiobook Mode is enabled) in the notification.

Admittedly this isn't as nice as using the volume buttons, but it doesn't appear that you can easily get a "long press" event from the volume buttons, and I didn't want to hack my own together.

![screenshot 09 45pm jan 23 2015 1 png](https://cloud.githubusercontent.com/assets/8142684/5886042/1a1a1bfa-a34a-11e4-918b-afb69b8d7a49.jpg)
