### ISSUE TITLE
Build of current version failing on f-droid

### ISSUE THREAD

**Issue by RealRancor** [smithdtyler/prettygoodmusicplayer#70]
Hi,

seems the current build on f-droid is failing with the following errors:

```
    [javac] Compiling 10 source files to /opt/fdroiddata/build/com.smithdtyler.prettygoodmusicplayer/bin/classes
    [javac] /opt/fdroiddata/build/com.smithdtyler.prettygoodmusicplayer/src/com/smithdtyler/prettygoodmusicplayer/AlbumList.java:120: error: cannot find symbol
    [javac]         String theme = sharedPref.getString("pref_theme", getString(R.string.light));
```
https://f-droid.org/wiki/page/com.smithdtyler.prettygoodmusicplayer/lastbuild_48

Are there any new requirements from your side? Havn't seen any obvious changes in the comparsion of the new versions to the older one:

https://github.com/smithdtyler/prettygoodmusicplayer/compare/3.1.7...3.1.8

**Comment by smithdtyler** [comment]
Weird... I'll check out out.

**Comment by smithdtyler** [comment]
Should be fixed now. I had missed a couple of files in my last commit.

**Comment by smithdtyler** [comment]
Please note, I just recreated the 3.1.8 tag, it was missing the same files.

**Comment by RealRancor** [comment]
Hi,

and thanks for the update. The next build cycle on f-droid is picking up the new tag so this should be fixed then. Closing this for now.
