### ISSUE TITLE
Exit button

### ISSUE THREAD

**Issue by xoyteam** [smithdtyler/prettygoodmusicplayer#78]
Add exit button in menu.
Add close button in system tray.

**Comment by smithdtyler** [comment]
Can you clarify what you mean by the system tray? I'm limited to 3 buttons in the notification (previous, pause/play, and next), so I can't add an 'exit' button there. 

I can definitely add one to the settings page though.

**Comment by xoyteam** [comment]
1) "system tray" - the notifications area.
2) The challenge is to turn off the player completely. You must press the "back" until we reach the root (i have a lot of subdirectories). And only then will we get a message "Are you sure?" ( No / Yes). Only after this application is completed in full - closed in the notification area.

3) Let me to offer you decisions:
Add exit button in menu.
Add close button in the notifications.

**Comment by smithdtyler** [comment]
OK. I will start by adding an 'exit' option to the menu. Thanks for the feedback!

**Comment by smithdtyler** [comment]
I've implemented the requested functionality in [https://github.com/smithdtyler/prettygoodmusicplayer/tree/exit_from_settings](this branch).

After some more testing I will merge it into master. Assuming I don't find any problems, it will be available on Google Play and F-Droid in a few days.

It looks like this:

![screenshot_2015-02-07-21-54-20](https://cloud.githubusercontent.com/assets/8142684/6095250/32974a02-af18-11e4-963f-9bd924897df2.png)

**Comment by smithdtyler** [comment]
Update: Following some discussion on Stackoverflow, I'm planning to make a "Stop" button which will stop the music playback service (removing the persistent icon). You'll still need to press "home" to leave the app.

[Link](https://stackoverflow.com/questions/28431204/is-my-approach-to-exiting-an-android-application-wise)

**Comment by smithdtyler** [comment]
Implemented in version 3.2.4
