### ISSUE TITLE
Hide Directories which have Cyrillic symbols

### ISSUE THREAD

**Issue by xoyteam** [smithdtyler/prettygoodmusicplayer#79]
Don't display directories is named have cirrylic sibols.
Sorry my english...

**Comment by smithdtyler** [comment]
I've gotten mixed requests on this one - someone else just filed a bug report asking that I show directories which have non-ascii characters. 

Are the directories "hidden"? That is, can you see them when you're looking at your phone using Windows Explorer?

**Comment by xoyteam** [comment]
On my phone (Nexus 4) no external flash card. All files are transmitted through the MTP. I not unlock root privileges - do not have access to the settings of the file attributes. From this it can be assumed that it is normal (not hidden) directories. And, yes, I can see them when viewed from the PC (Gnome File Browser).

I'm sorry, next time will be more careful before placing the issue.

**Comment by smithdtyler** [comment]
I'm planning to make this configurable. A fix will be include dint he next version.

**Comment by smithdtyler** [comment]
By the way - are you fluent in Russian? If so, would you be interested in helping provide a Russian translation?

**Comment by xoyteam** [comment]
Yes, I native speakers of Russian. I am willing to help with translation into Russian. But I'm not familiar with the development on Android. There are some files with strings for translation? You won't prompt with what to begin? my email: xoy(dot)mail(at)gmail(dot)com

**Comment by smithdtyler** [comment]
Did you decide this wasn't an issue?

**Comment by xoyteam** [comment]
I checked again and I think that is the problem https://github.com/smithdtyler/prettygoodmusicplayer/issues/46
