### ISSUE TITLE
russian translations

### ISSUE THREAD

**Issue by xoyteam** [smithdtyler/prettygoodmusicplayer#83]
Russian strings very long.
corrected file http://pastebin.com/hjQ3YR6y

![screenshot_2015-03-02-15-09-38](https://cloud.githubusercontent.com/assets/7936892/6441238/f1956a20-c0f6-11e4-837a-69981c9f53e8.png)

**Comment by smithdtyler** [comment]
I'm not sure how to address this - I can try to make the font smaller?
Otherwise we might need to find shorter translations.

**Comment by xoyteam** [comment]
I already corrected it.
in the message the link to the new file is placed above.

I will repeat, just in case: http://pastebin.com/hjQ3YR6y

**Comment by smithdtyler** [comment]
Thanks! I've applied your fix.
